### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Comment by henk-badenhorst** [comment]
@Shinigami92 Thanks for the contribution! Will add this to the next release.

**Comment by Shinigami92** [comment]
When will the next release be?

**Comment by henk-badenhorst** [comment]
@Shinigami92 Just added the definitions to the build and published the new version. Give it a test and let me know if there are any issues. Thanks!

**Comment by Shinigami92** [comment]
> @Shinigami92 Just added the definitions to the build and published the new version. Give it a test and let me know if there are any issues. Thanks!

Will do on monday

**Comment by Shinigami92** [comment]
Works fabulous, thx mate

**Comment by henk-badenhorst** [comment]
Great, thanks for the contribution!

**Pull request merged**
